// <auto-generated />
namespace sambit.DAL.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class Add_UserProfile : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Add_UserProfile));
        
        string IMigrationMetadata.Id
        {
            get { return "201211211750295_Add_UserProfile"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
